/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Confirm the process is up and the database answers.
         */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Me */
        get: operations["read_me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exercises */
        get: operations["list_exercises_api_exercises_get"];
        put?: never;
        /** Create Exercise */
        post: operations["create_exercise_api_exercises_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/by-slug/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Exercise By Slug
         * @description Resolve a url-safe slug to its exercise (the web Library's detail-page lookup).
         */
        get: operations["get_exercise_by_slug_api_exercises_by_slug__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/{exercise_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exercise */
        get: operations["get_exercise_api_exercises__exercise_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/{exercise_id}/illustration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ensure Illustration
         * @description On-demand fallback (docs/06): generate + persist this exercise's illustration if missing.
         *
         *     Returns the exercise; ``illustration_status`` is ``ready`` (with ``illustration_url``) on
         *     success, or ``generating`` if a batch run is already producing it. 503 if the image
         *     provider/Blob is unavailable.
         */
        post: operations["ensure_illustration_api_exercises__exercise_id__illustration_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_sessions_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_api_sessions__session_id__delete"];
        options?: never;
        head?: never;
        /** Update Session */
        patch: operations["update_session_api_sessions__session_id__patch"];
        trace?: never;
    };
    "/api/sessions/{session_id}/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log Set */
        post: operations["log_set_api_sessions__session_id__sets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sets/{set_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Set */
        delete: operations["delete_set_api_sets__set_id__delete"];
        options?: never;
        head?: never;
        /** Update Set */
        patch: operations["update_set_api_sets__set_id__patch"];
        trace?: never;
    };
    "/api/prs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Prs */
        get: operations["list_prs_api_prs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prs/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pr History */
        get: operations["pr_history_api_prs_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Skills Overview */
        get: operations["skills_overview_api_skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Skill Detail */
        get: operations["skill_detail_api_skills__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{slug}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upsert Skill Progress */
        put: operations["upsert_skill_progress_api_skills__slug__progress_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/volume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Volume */
        get: operations["volume_api_analytics_volume_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/frequency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Frequency */
        get: operations["frequency_api_analytics_frequency_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/login/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Login Google
         * @description Start Google sign-in: plant state/nonce/PKCE in a signed tx cookie, redirect to Google.
         */
        get: operations["login_google_oauth_login_google_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/callback/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Callback Google
         * @description Validate the Google callback, verify the ID token, upsert the user, set the session.
         */
        get: operations["callback_google_oauth_callback_google_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Clear the session cookie (idempotent).
         */
        post: operations["logout_oauth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/oauth-authorization-server": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Authorization Server Metadata */
        get: operations["authorization_server_metadata__well_known_oauth_authorization_server_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/oauth-protected-resource": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Protected Resource Metadata */
        get: operations["protected_resource_metadata__well_known_oauth_protected_resource_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Client */
        post: operations["register_client_oauth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Authorize */
        get: operations["authorize_oauth_authorize_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/authorize/consent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authorize Consent */
        post: operations["authorize_consent_oauth_authorize_consent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Token */
        post: operations["token_oauth_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthorizationServerMetadata
         * @description RFC 8414 AS metadata (``/.well-known/oauth-authorization-server``).
         */
        AuthorizationServerMetadata: {
            /** Issuer */
            issuer: string;
            /** Authorization Endpoint */
            authorization_endpoint: string;
            /** Token Endpoint */
            token_endpoint: string;
            /** Registration Endpoint */
            registration_endpoint: string;
            /** Response Types Supported */
            response_types_supported: string[];
            /** Grant Types Supported */
            grant_types_supported: string[];
            /** Code Challenge Methods Supported */
            code_challenge_methods_supported: string[];
            /** Token Endpoint Auth Methods Supported */
            token_endpoint_auth_methods_supported: string[];
            /** Scopes Supported */
            scopes_supported: string[];
        };
        /** Body_authorize_consent_oauth_authorize_consent_post */
        Body_authorize_consent_oauth_authorize_consent_post: {
            /** Approval */
            approval: string;
            /** Decision */
            decision: string;
        };
        /**
         * ClientRegistrationRequest
         * @description Inbound DCR body. Unknown RFC 7591 metadata fields are ignored, not rejected.
         */
        ClientRegistrationRequest: {
            /** Redirect Uris */
            redirect_uris: string[];
            /** Client Name */
            client_name?: string | null;
            /** Grant Types */
            grant_types?: string[] | null;
            /** Response Types */
            response_types?: string[] | null;
            /** Token Endpoint Auth Method */
            token_endpoint_auth_method?: string | null;
            /** Scope */
            scope?: string | null;
        };
        /**
         * ExerciseCreate
         * @description Create a custom exercise. ``slug`` is derived from ``name`` when omitted.
         */
        ExerciseCreate: {
            /** Name */
            name: string;
            /** Slug */
            slug?: string | null;
            /** Category */
            category?: string | null;
            /** Force */
            force?: string | null;
            /** Level */
            level?: string | null;
            /** Mechanic */
            mechanic?: string | null;
            /** Equipment */
            equipment?: string | null;
            /** Primary Muscles */
            primary_muscles?: string[];
            /** Secondary Muscles */
            secondary_muscles?: string[];
            /** Instructions */
            instructions?: string[];
        };
        /**
         * ExerciseDetailOut
         * @description Full detail: adds the how-to steps + provenance/timestamps.
         */
        ExerciseDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Category */
            category: string | null;
            /** Force */
            force: string | null;
            /** Level */
            level: string | null;
            /** Mechanic */
            mechanic: string | null;
            /** Equipment */
            equipment: string | null;
            /** Primary Muscles */
            primary_muscles: string[];
            /** Secondary Muscles */
            secondary_muscles: string[];
            /** Illustration Url */
            illustration_url: string | null;
            /** Illustration Status */
            illustration_status: string;
            /**
             * Is Custom
             * @default false
             */
            is_custom: boolean;
            /** Instructions */
            instructions: string[];
            /** Source */
            source: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ExerciseListOut */
        ExerciseListOut: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Items */
            items: components["schemas"]["ExerciseOut"][];
        };
        /**
         * ExerciseOut
         * @description Catalog summary (list rows + nested group headers).
         */
        ExerciseOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Category */
            category: string | null;
            /** Force */
            force: string | null;
            /** Level */
            level: string | null;
            /** Mechanic */
            mechanic: string | null;
            /** Equipment */
            equipment: string | null;
            /** Primary Muscles */
            primary_muscles: string[];
            /** Secondary Muscles */
            secondary_muscles: string[];
            /** Illustration Url */
            illustration_url: string | null;
            /** Illustration Status */
            illustration_status: string;
            /**
             * Is Custom
             * @default false
             */
            is_custom: boolean;
        };
        /**
         * ExerciseSetGroup
         * @description One exercise and its sets within a session detail.
         */
        ExerciseSetGroup: {
            exercise: components["schemas"]["ExerciseOut"];
            /** Sets */
            sets: components["schemas"]["SetOut"][];
        };
        /** FrequencyItem */
        FrequencyItem: {
            /**
             * Week Start
             * Format: date
             */
            week_start: string;
            /** Count */
            count: number;
        };
        /** FrequencyOut */
        FrequencyOut: {
            /** Weeks */
            weeks: number;
            /** Items */
            items: components["schemas"]["FrequencyItem"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoggedSetOut */
        LoggedSetOut: {
            set: components["schemas"]["SetOut"];
            pr: components["schemas"]["PrInfo"];
        };
        /** MeOut */
        MeOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string | null;
            /** Avatar Url */
            avatar_url: string | null;
            /** Unit Pref */
            unit_pref: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Login At */
            last_login_at: string | null;
        };
        /** PrHistoryOut */
        PrHistoryOut: {
            /**
             * Exercise Id
             * Format: uuid
             */
            exercise_id: string;
            /** Pr Type */
            pr_type: string;
            /** Items */
            items: components["schemas"]["SetOut"][];
        };
        /**
         * PrInfo
         * @description The PR verdict for the set that was just logged/updated.
         */
        PrInfo: {
            /** Is Pr */
            is_pr: boolean;
            /** Pr Type */
            pr_type: string | null;
            /** Previous Best */
            previous_best: number | null;
            /** New Value */
            new_value: number | null;
        };
        /** PrListOut */
        PrListOut: {
            /** Items */
            items: components["schemas"]["PrOut"][];
        };
        /** PrOut */
        PrOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Exercise Id
             * Format: uuid
             */
            exercise_id: string;
            /** Exercise Name */
            exercise_name: string;
            /** Exercise Slug */
            exercise_slug: string;
            /** Pr Type */
            pr_type: string;
            /** Value */
            value: number;
            /** Unit */
            unit: string;
            /**
             * Achieved At
             * Format: date-time
             */
            achieved_at: string;
            /** Session Id */
            session_id: string | null;
            /** Notes */
            notes: string | null;
        };
        /**
         * ProtectedResourceMetadata
         * @description RFC 9728 PRM (``/.well-known/oauth-protected-resource``).
         */
        ProtectedResourceMetadata: {
            /** Resource */
            resource: string;
            /** Authorization Servers */
            authorization_servers: string[];
            /** Scopes Supported */
            scopes_supported: string[];
            /** Bearer Methods Supported */
            bearer_methods_supported: string[];
        };
        /** SessionCreate */
        SessionCreate: {
            /**
             * Performed At
             * Format: date-time
             */
            performed_at: string;
            /** Title */
            title?: string | null;
            /** Type */
            type?: string | null;
            /** Notes */
            notes?: string | null;
            /** Duration Minutes */
            duration_minutes?: number | null;
        };
        /**
         * SessionDetailOut
         * @description Session plus its sets grouped by exercise (ordered by set number).
         */
        SessionDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string | null;
            /** Type */
            type: string | null;
            /**
             * Performed At
             * Format: date-time
             */
            performed_at: string;
            /** Notes */
            notes: string | null;
            /** Duration Minutes */
            duration_minutes: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Exercises */
            exercises: components["schemas"]["ExerciseSetGroup"][];
        };
        /** SessionListOut */
        SessionListOut: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Items */
            items: components["schemas"]["SessionOut"][];
        };
        /** SessionOut */
        SessionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string | null;
            /** Type */
            type: string | null;
            /**
             * Performed At
             * Format: date-time
             */
            performed_at: string;
            /** Notes */
            notes: string | null;
            /** Duration Minutes */
            duration_minutes: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * SessionUpdate
         * @description Patch session metadata; only supplied fields change.
         */
        SessionUpdate: {
            /** Performed At */
            performed_at?: string | null;
            /** Title */
            title?: string | null;
            /** Type */
            type?: string | null;
            /** Notes */
            notes?: string | null;
            /** Duration Minutes */
            duration_minutes?: number | null;
        };
        /**
         * SetCreate
         * @description Log a set within a session (the session id comes from the path).
         */
        SetCreate: {
            /**
             * Exercise Id
             * Format: uuid
             */
            exercise_id: string;
            /** Set Number */
            set_number: number;
            /** Weight Kg */
            weight_kg?: number | null;
            /** Reps */
            reps?: number | null;
            /** Hold Seconds */
            hold_seconds?: number | null;
            /** Rpe */
            rpe?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /** SetOut */
        SetOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Exercise Id
             * Format: uuid
             */
            exercise_id: string;
            /** Set Number */
            set_number: number;
            /** Weight Kg */
            weight_kg: number | null;
            /** Reps */
            reps: number | null;
            /** Hold Seconds */
            hold_seconds: number | null;
            /** Rpe */
            rpe: number | null;
            /** Is Pr */
            is_pr: boolean;
            /** Pr Type */
            pr_type: string | null;
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * SetUpdate
         * @description Patch a set's metrics; only supplied fields change (PR is recomputed).
         */
        SetUpdate: {
            /** Set Number */
            set_number?: number | null;
            /** Weight Kg */
            weight_kg?: number | null;
            /** Reps */
            reps?: number | null;
            /** Hold Seconds */
            hold_seconds?: number | null;
            /** Rpe */
            rpe?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /** SkillDetailOut */
        SkillDetailOut: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Total Stages */
            total_stages: number;
            /** Stages */
            stages: {
                [key: string]: unknown;
            }[] | null;
            /** Related Exercise Id */
            related_exercise_id: string | null;
            progress: components["schemas"]["SkillProgressOut"] | null;
        };
        /**
         * SkillOverviewItem
         * @description A skill flattened with the user's progress (defaults when not started).
         */
        SkillOverviewItem: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Total Stages */
            total_stages: number;
            /** Current Stage */
            current_stage: number;
            /** Stage Name */
            stage_name: string | null;
            /** Progress Percent */
            progress_percent: number;
            /** Notes */
            notes: string | null;
            /** Updated At */
            updated_at: string | null;
        };
        /** SkillProgressOut */
        SkillProgressOut: {
            /** Current Stage */
            current_stage: number;
            /** Stage Name */
            stage_name: string | null;
            /** Progress Percent */
            progress_percent: number;
            /** Notes */
            notes: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SkillProgressUpsert */
        SkillProgressUpsert: {
            /** Current Stage */
            current_stage: number;
            /** Progress Percent */
            progress_percent: number;
            /** Stage Name */
            stage_name?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** SkillsOverviewOut */
        SkillsOverviewOut: {
            /** Items */
            items: components["schemas"]["SkillOverviewItem"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VolumeItem */
        VolumeItem: {
            /**
             * Exercise Id
             * Format: uuid
             */
            exercise_id: string;
            /** Exercise Name */
            exercise_name: string;
            /** Total Sets */
            total_sets: number;
            /** Total Reps */
            total_reps: number;
            /** Total Tonnage Kg */
            total_tonnage_kg: number | null;
        };
        /** VolumeOut */
        VolumeOut: {
            /**
             * Date From
             * Format: date-time
             */
            date_from: string;
            /**
             * Date To
             * Format: date-time
             */
            date_to: string;
            /** Items */
            items: components["schemas"]["VolumeItem"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    read_me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    list_exercises_api_exercises_get: {
        parameters: {
            query?: {
                /** @description Free-text match on name */
                q?: string | null;
                muscle?: string | null;
                equipment?: string | null;
                category?: string | null;
                level?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_exercise_api_exercises_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exercise_by_slug_api_exercises_by_slug__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exercise_api_exercises__exercise_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ensure_illustration_api_exercises__exercise_id__illustration_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_sessions_get: {
        parameters: {
            query?: {
                type?: string | null;
                from?: string | null;
                to?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_session_api_sessions__session_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_set_api_sessions__session_id__sets_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoggedSetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_set_api_sets__set_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_set_api_sets__set_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoggedSetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_prs_api_prs_get: {
        parameters: {
            query?: {
                exercise_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pr_history_api_prs_history_get: {
        parameters: {
            query: {
                exercise_id: string;
                pr_type: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrHistoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    skills_overview_api_skills_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillsOverviewOut"];
                };
            };
        };
    };
    skill_detail_api_skills__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_skill_progress_api_skills__slug__progress_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillProgressUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillProgressOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    volume_api_analytics_volume_get: {
        parameters: {
            query: {
                from: string;
                to: string;
                exercise_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolumeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    frequency_api_analytics_frequency_get: {
        parameters: {
            query?: {
                weeks?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrequencyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_google_oauth_login_google_get: {
        parameters: {
            query?: {
                return_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    callback_google_oauth_callback_google_get: {
        parameters: {
            query?: {
                code?: string | null;
                state?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_oauth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    authorization_server_metadata__well_known_oauth_authorization_server_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorizationServerMetadata"];
                };
            };
        };
    };
    protected_resource_metadata__well_known_oauth_protected_resource_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProtectedResourceMetadata"];
                };
            };
        };
    };
    register_client_oauth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientRegistrationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    authorize_oauth_authorize_get: {
        parameters: {
            query?: {
                response_type?: string | null;
                client_id?: string | null;
                redirect_uri?: string | null;
                scope?: string | null;
                state?: string | null;
                code_challenge?: string | null;
                code_challenge_method?: string | null;
                resource?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    authorize_consent_oauth_authorize_consent_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_authorize_consent_oauth_authorize_consent_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    token_oauth_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
