/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Confirm the process is up and the database answers.
         */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Me */
        get: operations["read_me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_api_me_patch"];
        trace?: never;
    };
    "/api/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exercises */
        get: operations["list_exercises_api_exercises_get"];
        put?: never;
        /** Create Exercise */
        post: operations["create_exercise_api_exercises_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/by-slug/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Exercise By Slug
         * @description Resolve a url-safe slug to its exercise (the web Library's detail-page lookup).
         */
        get: operations["get_exercise_by_slug_api_exercises_by_slug__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/{exercise_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exercise */
        get: operations["get_exercise_api_exercises__exercise_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Exercise
         * @description Soft-delete a custom exercise, refusing to orphan the sets that reference it.
         */
        delete: operations["delete_exercise_api_exercises__exercise_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Exercise
         * @description Edit a **custom** exercise. Renaming regenerates the slug, keeping the old one as an alias.
         */
        patch: operations["update_exercise_api_exercises__exercise_id__patch"];
        trace?: never;
    };
    "/api/exercises/{exercise_id}/illustration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ensure Illustration
         * @description On-demand fallback (docs/06): generate + persist this exercise's illustration if missing.
         *
         *     Returns the exercise; ``illustration_status`` is ``ready`` (with ``illustration_url``) on
         *     success, or ``generating`` if a batch run is already producing it. 503 if the image
         *     provider/Blob is unavailable.
         */
        post: operations["ensure_illustration_api_exercises__exercise_id__illustration_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_sessions_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Active Session
         * @description The in-progress session, or `null`. May finish sessions abandoned >12 h (see the service).
         */
        get: operations["get_active_session_api_sessions_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/with-sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Session With Sets
         * @description Create a session and its sets in one transaction — all or nothing.
         */
        post: operations["create_session_with_sets_api_sessions_with_sets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Session
         * @description Soft-delete a session and (with `cascade`) its sets, recalculating every PR affected.
         */
        delete: operations["delete_session_api_sessions__session_id__delete"];
        options?: never;
        head?: never;
        /** Update Session */
        patch: operations["update_session_api_sessions__session_id__patch"];
        trace?: never;
    };
    "/api/sessions/{session_id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finish Session
         * @description Close a session and store its duration. Idempotent — finishing a finished one is a no-op.
         */
        post: operations["finish_session_api_sessions__session_id__finish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/sets/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log Sets
         * @description Log many sets into one session transactionally, with a PR verdict for each.
         */
        post: operations["log_sets_api_sessions__session_id__sets_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log Set */
        post: operations["log_set_api_sessions__session_id__sets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sets/{set_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Set
         * @description Soft-delete a set and recompute its exercise's records.
         *
         *     Returns the removed row rather than 204 so the caller has the id to `restore` with, and can
         *     see it really was this set. The record it may have held falls back to the next best.
         */
        delete: operations["delete_set_api_sets__set_id__delete"];
        options?: never;
        head?: never;
        /** Update Set */
        patch: operations["update_set_api_sets__set_id__patch"];
        trace?: never;
    };
    "/api/prs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Prs */
        get: operations["list_prs_api_prs_get"];
        put?: never;
        /**
         * Log Pr
         * @description Record a PR by hand — the REST twin of the MCP ``log_pr`` tool.
         *
         *     For records a logged set cannot express: an estimated 1RM, a hold timed outside a session, or
         *     a PR migrated from another app. Overwrites whatever is stored for this exercise + metric.
         */
        post: operations["log_pr_api_prs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prs/{pr_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Pr
         * @description Withdraw a hand-entered record; the next best becomes current rather than leaving a gap.
         */
        delete: operations["delete_pr_api_prs__pr_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Pr
         * @description Correct a hand-entered record in place, without the delete-and-reinsert dance.
         */
        patch: operations["update_pr_api_prs__pr_id__patch"];
        trace?: never;
    };
    "/api/prs/history/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Pr History Entry
         * @description Remove one chronology entry, then rebuild the record from what is left.
         */
        delete: operations["delete_pr_history_entry_api_prs_history__entry_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prs/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pr History */
        get: operations["pr_history_api_prs_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Skills Overview */
        get: operations["skills_overview_api_skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Skill Detail */
        get: operations["skill_detail_api_skills__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{slug}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upsert Skill Progress */
        put: operations["upsert_skill_progress_api_skills__slug__progress_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/volume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Volume */
        get: operations["volume_api_analytics_volume_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/frequency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Frequency */
        get: operations["frequency_api_analytics_frequency_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Connections */
        get: operations["list_connections_api_connections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/{client_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Connection */
        delete: operations["revoke_connection_api_connections__client_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/corrections/recalculate-prs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recalculate Prs
         * @description Rebuild personal records and their chronology from the live sets + hand-entered claims.
         */
        post: operations["recalculate_prs_api_corrections_recalculate_prs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/corrections/verify-prs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify Prs
         * @description Read-only: report any exercise whose record tables disagree with themselves.
         */
        get: operations["verify_prs_api_corrections_verify_prs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/corrections/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore
         * @description Undo a soft delete and rebuild whatever records depended on the row being gone.
         */
        post: operations["restore_api_corrections_restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/corrections/purge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Purge
         * @description Hard-delete rows soft-deleted longer ago than ``older_than_days``. Irreversible.
         */
        post: operations["purge_api_corrections_purge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/login/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Login Google
         * @description Start Google sign-in: plant state/nonce/PKCE in a signed tx cookie, redirect to Google.
         */
        get: operations["login_google_oauth_login_google_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/callback/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Callback Google
         * @description Validate the Google callback, verify the ID token, upsert the user, set the session.
         */
        get: operations["callback_google_oauth_callback_google_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Clear the session cookie (idempotent).
         */
        post: operations["logout_oauth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/oauth-authorization-server": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Authorization Server Metadata */
        get: operations["authorization_server_metadata__well_known_oauth_authorization_server_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/oauth-protected-resource": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Protected Resource Metadata */
        get: operations["protected_resource_metadata__well_known_oauth_protected_resource_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Client */
        post: operations["register_client_oauth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Authorize */
        get: operations["authorize_oauth_authorize_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/authorize/consent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authorize Consent */
        post: operations["authorize_consent_oauth_authorize_consent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Token */
        post: operations["token_oauth_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActiveSessionOut
         * @description The user's in-progress session, or ``null`` when they aren't training.
         *
         *     Wrapped rather than returned bare so "no active session" is an ordinary 200 with a
         *     typed, nullable field — clients poll this on every screen and a 404 would be noise.
         *
         *     ``set_count`` lives here and **not** on :class:`SessionOut`, which is validated straight
         *     off raw ORM rows at every other call site and would raise on a required field with no
         *     matching attribute. It is here because it is what the callers of this endpoint actually
         *     need next: both the docked session bar and the home workout card say "N sets" and would
         *     otherwise fetch the entire session detail — every set plus full exercise rows — to count.
         */
        ActiveSessionOut: {
            session: components["schemas"]["SessionOut"] | null;
            /** Set Count */
            set_count: number;
        };
        /**
         * AuthorizationServerMetadata
         * @description RFC 8414 AS metadata (``/.well-known/oauth-authorization-server``).
         */
        AuthorizationServerMetadata: {
            /** Issuer */
            issuer: string;
            /** Authorization Endpoint */
            authorization_endpoint: string;
            /** Token Endpoint */
            token_endpoint: string;
            /** Registration Endpoint */
            registration_endpoint: string;
            /** Response Types Supported */
            response_types_supported: string[];
            /** Grant Types Supported */
            grant_types_supported: string[];
            /** Code Challenge Methods Supported */
            code_challenge_methods_supported: string[];
            /** Token Endpoint Auth Methods Supported */
            token_endpoint_auth_methods_supported: string[];
            /** Scopes Supported */
            scopes_supported: string[];
        };
        /** Body_authorize_consent_oauth_authorize_consent_post */
        Body_authorize_consent_oauth_authorize_consent_post: {
            /** Approval */
            approval: string;
            /** Decision */
            decision: string;
        };
        /**
         * ClientRegistrationRequest
         * @description Inbound DCR body. Unknown RFC 7591 metadata fields are ignored, not rejected.
         */
        ClientRegistrationRequest: {
            /** Redirect Uris */
            redirect_uris: string[];
            /** Client Name */
            client_name?: string | null;
            /** Grant Types */
            grant_types?: string[] | null;
            /** Response Types */
            response_types?: string[] | null;
            /** Token Endpoint Auth Method */
            token_endpoint_auth_method?: string | null;
            /** Scope */
            scope?: string | null;
        };
        /** ConnectionListOut */
        ConnectionListOut: {
            /** Items */
            items: components["schemas"]["ConnectionOut"][];
        };
        /**
         * ConnectionOut
         * @description A connected chat client + the state of the user's grant to it.
         */
        ConnectionOut: {
            /** Client Id */
            client_id: string;
            /** Client Name */
            client_name: string | null;
            /** Scope */
            scope: string | null;
            /**
             * Connected At
             * Format: date-time
             */
            connected_at: string;
            /** Last Active At */
            last_active_at: string | null;
            /** Active Token Count */
            active_token_count: number;
        };
        /**
         * ExerciseCreate
         * @description Create a custom exercise. ``slug`` is derived from ``name`` when omitted.
         */
        ExerciseCreate: {
            /** Name */
            name: string;
            /** Slug */
            slug?: string | null;
            /** Category */
            category?: string | null;
            /** Force */
            force?: string | null;
            /** Level */
            level?: string | null;
            /** Mechanic */
            mechanic?: string | null;
            /** Equipment */
            equipment?: string | null;
            /** Primary Muscles */
            primary_muscles?: string[];
            /** Secondary Muscles */
            secondary_muscles?: string[];
            /** Instructions */
            instructions?: string[];
        };
        /**
         * ExerciseDeleteOut
         * @description What a custom-exercise delete did — or, with ``dry_run``, would have done.
         */
        ExerciseDeleteOut: {
            exercise: components["schemas"]["ExerciseOut"];
            /** Set Count */
            set_count: number;
            reassigned_to: components["schemas"]["ExerciseOut"] | null;
            /** Dry Run */
            dry_run: boolean;
        };
        /**
         * ExerciseDetailOut
         * @description Full detail: adds the how-to steps + provenance/timestamps.
         */
        ExerciseDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Category */
            category: string | null;
            /** Force */
            force: string | null;
            /** Level */
            level: string | null;
            /** Mechanic */
            mechanic: string | null;
            /** Equipment */
            equipment: string | null;
            /** Primary Muscles */
            primary_muscles: string[];
            /** Secondary Muscles */
            secondary_muscles: string[];
            /** Illustration Url */
            illustration_url: string | null;
            /** Illustration Url Light */
            illustration_url_light: string | null;
            /** Illustration Status */
            illustration_status: string;
            /**
             * Is Custom
             * @default false
             */
            is_custom?: boolean;
            /** Instructions */
            instructions: string[];
            /** Source */
            source: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ExerciseListOut */
        ExerciseListOut: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Items */
            items: components["schemas"]["ExerciseOut"][];
        };
        /**
         * ExerciseOut
         * @description Catalog summary (list rows + nested group headers).
         */
        ExerciseOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Category */
            category: string | null;
            /** Force */
            force: string | null;
            /** Level */
            level: string | null;
            /** Mechanic */
            mechanic: string | null;
            /** Equipment */
            equipment: string | null;
            /** Primary Muscles */
            primary_muscles: string[];
            /** Secondary Muscles */
            secondary_muscles: string[];
            /** Illustration Url */
            illustration_url: string | null;
            /** Illustration Url Light */
            illustration_url_light: string | null;
            /** Illustration Status */
            illustration_status: string;
            /**
             * Is Custom
             * @default false
             */
            is_custom?: boolean;
        };
        /**
         * ExerciseSetGroup
         * @description One exercise and its sets within a session detail.
         */
        ExerciseSetGroup: {
            exercise: components["schemas"]["ExerciseOut"];
            /** Sets */
            sets: components["schemas"]["SetOut"][];
        };
        /**
         * ExerciseUpdate
         * @description Patch a **custom** exercise; only supplied fields change.
         *
         *     No ``slug``: it is derived from ``name``, so the two cannot drift. Renaming keeps the old slug
         *     resolvable as an alias.
         */
        ExerciseUpdate: {
            /** Name */
            name?: string | null;
            /** Category */
            category?: string | null;
            /** Force */
            force?: string | null;
            /** Level */
            level?: string | null;
            /** Mechanic */
            mechanic?: string | null;
            /** Equipment */
            equipment?: string | null;
            /** Primary Muscles */
            primary_muscles?: string[] | null;
            /** Secondary Muscles */
            secondary_muscles?: string[] | null;
            /** Instructions */
            instructions?: string[] | null;
        };
        /** FrequencyItem */
        FrequencyItem: {
            /**
             * Week Start
             * Format: date
             */
            week_start: string;
            /** Count */
            count: number;
        };
        /** FrequencyOut */
        FrequencyOut: {
            /** Weeks */
            weeks: number;
            /** Items */
            items: components["schemas"]["FrequencyItem"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IntegrityOut */
        IntegrityOut: {
            /** Ok */
            ok: boolean;
            /** Checked Exercises */
            checked_exercises: number;
            /** Problems */
            problems: components["schemas"]["IntegrityProblemOut"][];
        };
        /** IntegrityProblemOut */
        IntegrityProblemOut: {
            /**
             * Exercise Id
             * Format: uuid
             */
            exercise_id: string;
            /** Exercise Name */
            exercise_name: string;
            /** Pr Type */
            pr_type: string;
            /** Kind */
            kind: string;
            /** Detail */
            detail: string;
        };
        /** LoggedSetOut */
        LoggedSetOut: {
            set: components["schemas"]["SetOut"];
            pr: components["schemas"]["PrInfo"];
        };
        /** LoggedSetsOut */
        LoggedSetsOut: {
            /** Items */
            items: components["schemas"]["LoggedSetOut"][];
        };
        /** MeOut */
        MeOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string | null;
            /** Avatar Url */
            avatar_url: string | null;
            /** Unit Pref */
            unit_pref: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Login At */
            last_login_at: string | null;
        };
        /**
         * MeUpdate
         * @description Patch the current user's display preferences (Settings → units, docs/07).
         */
        MeUpdate: {
            /**
             * Unit Pref
             * @enum {string}
             */
            unit_pref: "kg" | "lb";
        };
        /**
         * MetricResultOut
         * @description What a rebuild produced for one (exercise, metric).
         */
        MetricResultOut: {
            /**
             * Exercise Id
             * Format: uuid
             */
            exercise_id: string;
            /** Exercise Name */
            exercise_name: string;
            /** Pr Type */
            pr_type: string;
            /** Value */
            value: number | null;
            /** Source */
            source: string | null;
            /** Entries */
            entries: number;
            /** Changed */
            changed: boolean;
        };
        /**
         * PrCreate
         * @description A hand-entered record. ``unit`` is not a field — it follows from ``pr_type``.
         */
        PrCreate: {
            /**
             * Exercise Id
             * Format: uuid
             */
            exercise_id: string;
            /** Pr Type */
            pr_type: string;
            /** Value */
            value: number;
            /**
             * Achieved At
             * Format: date-time
             */
            achieved_at: string;
            /** Session Id */
            session_id?: string | null;
            /** Notes */
            notes?: string | null;
            /** Client Key */
            client_key?: string | null;
        };
        /**
         * PrDeleteOut
         * @description What is standing after a record was withdrawn — ``null`` if nothing supports one.
         */
        PrDeleteOut: {
            standing: components["schemas"]["PrOut"] | null;
        };
        /**
         * PrHistoryItem
         * @description One entry in a record's chronology, auto or manual.
         *
         *     This replaces the ``SetOut`` this endpoint used to return. A manual record has no set behind
         *     it, so a set-shaped payload could not represent one — which is precisely why manual entries
         *     were missing from PR history before.
         */
        PrHistoryItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Pr Type */
            pr_type: string;
            /** Value */
            value: number;
            /** Unit */
            unit: string;
            /**
             * Achieved At
             * Format: date-time
             */
            achieved_at: string;
            /** Source */
            source: string;
            /** Set Id */
            set_id: string | null;
            /** Session Id */
            session_id: string | null;
            /** Notes */
            notes: string | null;
            /** Counted */
            counted: boolean;
            /** Deleted At */
            deleted_at: string | null;
        };
        /** PrHistoryOut */
        PrHistoryOut: {
            /**
             * Exercise Id
             * Format: uuid
             */
            exercise_id: string;
            /** Pr Type */
            pr_type: string;
            /**
             * Items
             * @description Oldest first; manual and auto entries interleaved chronologically.
             */
            items: components["schemas"]["PrHistoryItem"][];
        };
        /**
         * PrInfo
         * @description The PR verdict for the set that was just logged/updated.
         */
        PrInfo: {
            /** Is Pr */
            is_pr: boolean;
            /** Pr Type */
            pr_type: string | null;
            /** Previous Best */
            previous_best: number | null;
            /** New Value */
            new_value: number | null;
        };
        /** PrListOut */
        PrListOut: {
            /** Items */
            items: components["schemas"]["PrOut"][];
        };
        /** PrOut */
        PrOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Exercise Id
             * Format: uuid
             */
            exercise_id: string;
            /** Exercise Name */
            exercise_name: string;
            /** Exercise Slug */
            exercise_slug: string;
            /** Pr Type */
            pr_type: string;
            /** Value */
            value: number;
            /** Unit */
            unit: string;
            /**
             * Achieved At
             * Format: date-time
             */
            achieved_at: string;
            /** Session Id */
            session_id: string | null;
            /** Notes */
            notes: string | null;
            /** Source */
            source: string;
            /** Illustration Url */
            illustration_url: string | null;
            /** Illustration Status */
            illustration_status: string;
            /** Is Custom */
            is_custom: boolean;
        };
        /**
         * PrUpdate
         * @description Correct a hand-entered record in place. Only supplied fields change.
         */
        PrUpdate: {
            /** Value */
            value?: number | null;
            /** Achieved At */
            achieved_at?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Clear Notes
             * @default false
             */
            clear_notes?: boolean;
        };
        /**
         * ProtectedResourceMetadata
         * @description RFC 9728 PRM (``/.well-known/oauth-protected-resource``).
         */
        ProtectedResourceMetadata: {
            /** Resource */
            resource: string;
            /** Authorization Servers */
            authorization_servers: string[];
            /** Scopes Supported */
            scopes_supported: string[];
            /** Bearer Methods Supported */
            bearer_methods_supported: string[];
        };
        /** PurgeIn */
        PurgeIn: {
            /** Older Than Days */
            older_than_days: number;
            /**
             * Dry Run
             * @default false
             */
            dry_run?: boolean;
        };
        /** PurgeOut */
        PurgeOut: {
            /** Older Than Days */
            older_than_days: number;
            /** Total */
            total: number;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Dry Run */
            dry_run: boolean;
        };
        /** RecalculationOut */
        RecalculationOut: {
            /** Exercises */
            exercises: number;
            /** Changed */
            changed: components["schemas"]["MetricResultOut"][];
            /** Metrics */
            metrics: components["schemas"]["MetricResultOut"][];
            /**
             * Dry Run
             * @default false
             */
            dry_run?: boolean;
        };
        /** RestoreIn */
        RestoreIn: {
            /** Entity Type */
            entity_type: string;
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
        };
        /** RestoreOut */
        RestoreOut: {
            /** Entity Type */
            entity_type: string;
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Exercises Recalculated */
            exercises_recalculated: number;
        };
        /**
         * RevokeConnectionOut
         * @description How many of the user's tokens were revoked for the client.
         */
        RevokeConnectionOut: {
            /** Client Id */
            client_id: string;
            /** Revoked Access */
            revoked_access: number;
            /** Revoked Refresh */
            revoked_refresh: number;
        };
        /** SessionCreate */
        SessionCreate: {
            /**
             * Performed At
             * Format: date-time
             */
            performed_at: string;
            /** Title */
            title?: string | null;
            /** Type */
            type?: string | null;
            /** Notes */
            notes?: string | null;
            /** Duration Minutes */
            duration_minutes?: number | null;
            /** Client Key */
            client_key?: string | null;
        };
        /**
         * SessionDeleteOut
         * @description What a delete did — or, with ``dry_run``, would have done.
         */
        SessionDeleteOut: {
            session: components["schemas"]["SessionOut"];
            /** Set Count */
            set_count: number;
            /** Exercises Recalculated */
            exercises_recalculated: number;
            /** Dry Run */
            dry_run: boolean;
        };
        /**
         * SessionDetailOut
         * @description Session plus its sets grouped by exercise (ordered by set number).
         */
        SessionDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string | null;
            /** Type */
            type: string | null;
            /**
             * Performed At
             * Format: date-time
             */
            performed_at: string;
            /** Ended At */
            ended_at: string | null;
            /** Notes */
            notes: string | null;
            /** Duration Minutes */
            duration_minutes: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Exercises */
            exercises: components["schemas"]["ExerciseSetGroup"][];
        };
        /** SessionListOut */
        SessionListOut: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Items */
            items: components["schemas"]["SessionOut"][];
        };
        /** SessionOut */
        SessionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string | null;
            /** Type */
            type: string | null;
            /**
             * Performed At
             * Format: date-time
             */
            performed_at: string;
            /** Ended At */
            ended_at: string | null;
            /** Notes */
            notes: string | null;
            /** Duration Minutes */
            duration_minutes: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * SessionUpdate
         * @description Patch session metadata; only supplied fields change.
         *
         *     ``clear_notes`` rather than a nullable ``notes``: in a partial update ``null`` already means
         *     "leave alone", so emptying a field needs its own word.
         */
        SessionUpdate: {
            /** Performed At */
            performed_at?: string | null;
            /** Ended At */
            ended_at?: string | null;
            /** Title */
            title?: string | null;
            /** Type */
            type?: string | null;
            /** Notes */
            notes?: string | null;
            /** Duration Minutes */
            duration_minutes?: number | null;
            /**
             * Clear Notes
             * @default false
             */
            clear_notes?: boolean;
        };
        /**
         * SessionWithSetsCreate
         * @description Create a session and its sets in one transaction (all or nothing).
         */
        SessionWithSetsCreate: {
            /**
             * Performed At
             * Format: date-time
             */
            performed_at: string;
            /** Title */
            title?: string | null;
            /** Type */
            type?: string | null;
            /** Notes */
            notes?: string | null;
            /** Duration Minutes */
            duration_minutes?: number | null;
            /** Client Key */
            client_key?: string | null;
            /** Sets */
            sets: components["schemas"]["SetCreate"][];
        };
        /** SessionWithSetsOut */
        SessionWithSetsOut: {
            session: components["schemas"]["SessionOut"];
            /** Sets */
            sets: components["schemas"]["LoggedSetOut"][];
        };
        /**
         * SetBulkCreate
         * @description Log many sets into one session as a single transaction (all or nothing).
         */
        SetBulkCreate: {
            /** Sets */
            sets: components["schemas"]["SetCreate"][];
        };
        /**
         * SetCreate
         * @description Log a set within a session (the session id comes from the path).
         */
        SetCreate: {
            /**
             * Exercise Id
             * Format: uuid
             */
            exercise_id: string;
            /** Set Number */
            set_number: number;
            /** Weight Kg */
            weight_kg?: number | null;
            /** Reps */
            reps?: number | null;
            /** Hold Seconds */
            hold_seconds?: number | null;
            /** Rpe */
            rpe?: number | null;
            /** Notes */
            notes?: string | null;
            /**
             * Is Backfill
             * @default false
             */
            is_backfill?: boolean;
            /** Client Key */
            client_key?: string | null;
        };
        /** SetOut */
        SetOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Exercise Id
             * Format: uuid
             */
            exercise_id: string;
            /** Set Number */
            set_number: number;
            /** Weight Kg */
            weight_kg: number | null;
            /** Reps */
            reps: number | null;
            /** Hold Seconds */
            hold_seconds: number | null;
            /** Rpe */
            rpe: number | null;
            /** Is Pr */
            is_pr: boolean;
            /** Pr Type */
            pr_type: string | null;
            /** Notes */
            notes: string | null;
            /** Is Backfill */
            is_backfill: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * SetUpdate
         * @description Patch a set's metrics; only supplied fields change (PR is recomputed).
         */
        SetUpdate: {
            /** Set Number */
            set_number?: number | null;
            /** Weight Kg */
            weight_kg?: number | null;
            /** Reps */
            reps?: number | null;
            /** Hold Seconds */
            hold_seconds?: number | null;
            /** Rpe */
            rpe?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /** SkillDetailOut */
        SkillDetailOut: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Total Stages */
            total_stages: number;
            /** Stages */
            stages: {
                [key: string]: unknown;
            }[] | null;
            /** Related Exercise Id */
            related_exercise_id: string | null;
            progress: components["schemas"]["SkillProgressOut"] | null;
        };
        /**
         * SkillOverviewItem
         * @description A skill flattened with the user's progress (defaults when not started).
         */
        SkillOverviewItem: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Total Stages */
            total_stages: number;
            /** Current Stage */
            current_stage: number;
            /** Stage Name */
            stage_name: string | null;
            /** Progress Percent */
            progress_percent: number;
            /** Notes */
            notes: string | null;
            /** Updated At */
            updated_at: string | null;
        };
        /** SkillProgressOut */
        SkillProgressOut: {
            /** Current Stage */
            current_stage: number;
            /** Stage Name */
            stage_name: string | null;
            /** Progress Percent */
            progress_percent: number;
            /** Notes */
            notes: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SkillProgressUpsert */
        SkillProgressUpsert: {
            /** Current Stage */
            current_stage: number;
            /** Progress Percent */
            progress_percent: number;
            /** Stage Name */
            stage_name?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** SkillsOverviewOut */
        SkillsOverviewOut: {
            /** Items */
            items: components["schemas"]["SkillOverviewItem"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VolumeItem */
        VolumeItem: {
            /**
             * Exercise Id
             * Format: uuid
             */
            exercise_id: string;
            /** Exercise Name */
            exercise_name: string;
            /** Total Sets */
            total_sets: number;
            /** Total Reps */
            total_reps: number;
            /** Total Tonnage Kg */
            total_tonnage_kg: number | null;
        };
        /** VolumeOut */
        VolumeOut: {
            /**
             * Date From
             * Format: date-time
             */
            date_from: string;
            /**
             * Date To
             * Format: date-time
             */
            date_to: string;
            /** Items */
            items: components["schemas"]["VolumeItem"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    read_me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    update_me_api_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exercises_api_exercises_get: {
        parameters: {
            query?: {
                /** @description Free-text match on name */
                q?: string | null;
                muscle?: string | null;
                equipment?: string | null;
                category?: string | null;
                level?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_exercise_api_exercises_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exercise_by_slug_api_exercises_by_slug__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exercise_api_exercises__exercise_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_exercise_api_exercises__exercise_id__delete: {
        parameters: {
            query?: {
                reassign_to?: string | null;
                dry_run?: boolean;
            };
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseDeleteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_exercise_api_exercises__exercise_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ensure_illustration_api_exercises__exercise_id__illustration_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_sessions_get: {
        parameters: {
            query?: {
                type?: string | null;
                from?: string | null;
                to?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_active_session_api_sessions_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveSessionOut"];
                };
            };
        };
    };
    create_session_with_sets_api_sessions_with_sets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionWithSetsCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionWithSetsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_sessions__session_id__delete: {
        parameters: {
            query?: {
                cascade?: boolean;
                dry_run?: boolean;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDeleteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_session_api_sessions__session_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finish_session_api_sessions__session_id__finish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_sets_api_sessions__session_id__sets_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetBulkCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoggedSetsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_set_api_sessions__session_id__sets_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoggedSetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_set_api_sets__set_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_set_api_sets__set_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoggedSetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_prs_api_prs_get: {
        parameters: {
            query?: {
                exercise_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_pr_api_prs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_pr_api_prs__pr_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pr_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrDeleteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_pr_api_prs__pr_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pr_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_pr_history_entry_api_prs_history__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrHistoryItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pr_history_api_prs_history_get: {
        parameters: {
            query: {
                exercise_id: string;
                pr_type: string;
                include_deleted?: boolean;
                include_uncounted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrHistoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    skills_overview_api_skills_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillsOverviewOut"];
                };
            };
        };
    };
    skill_detail_api_skills__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_skill_progress_api_skills__slug__progress_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillProgressUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillProgressOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    volume_api_analytics_volume_get: {
        parameters: {
            query: {
                from: string;
                to: string;
                exercise_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolumeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    frequency_api_analytics_frequency_get: {
        parameters: {
            query?: {
                weeks?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrequencyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_connections_api_connections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionListOut"];
                };
            };
        };
    };
    revoke_connection_api_connections__client_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeConnectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recalculate_prs_api_corrections_recalculate_prs_post: {
        parameters: {
            query?: {
                exercise_id?: string | null;
                pr_type?: string | null;
                dry_run?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecalculationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_prs_api_corrections_verify_prs_get: {
        parameters: {
            query?: {
                exercise_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_api_corrections_restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestoreIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestoreOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    purge_api_corrections_purge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PurgeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurgeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_google_oauth_login_google_get: {
        parameters: {
            query?: {
                return_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    callback_google_oauth_callback_google_get: {
        parameters: {
            query?: {
                code?: string | null;
                state?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_oauth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    authorization_server_metadata__well_known_oauth_authorization_server_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorizationServerMetadata"];
                };
            };
        };
    };
    protected_resource_metadata__well_known_oauth_protected_resource_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProtectedResourceMetadata"];
                };
            };
        };
    };
    register_client_oauth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientRegistrationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    authorize_oauth_authorize_get: {
        parameters: {
            query?: {
                response_type?: string | null;
                client_id?: string | null;
                redirect_uri?: string | null;
                scope?: string | null;
                state?: string | null;
                code_challenge?: string | null;
                code_challenge_method?: string | null;
                resource?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    authorize_consent_oauth_authorize_consent_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_authorize_consent_oauth_authorize_consent_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    token_oauth_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
